[build-system]
requires = ["hatchling>=1.0"]
build-backend = "hatchling.build"

[project]
name = "plex-playlist-manager"
version = "0.1.0"
description = ""
authors = [{ name = "James Berkheimer", email = "james.berkheimer@gmail.com" }]
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.30.0",
    "jinja2>=3.1.0",
    "itsdangerous>=2.1.0",
    "python-multipart>=0.0.9",
]

[tool.hatch.build.targets.wheel]
packages = ["backend", "frontend"]

[project.scripts]
ppm = "PATH_TO_ENTRY_SCRIPT"

[project.optional-dependencies]
dev = []